name = "aimagica-pages"
compatibility_date = "2024-01-01"

# Cloudflare Pages 配置
pages_build_output_dir = "./out"

# 构建配置 - Pages 特定格式
[pages]
build_command = "npm run build:pages"
destination = "./out"

# Pages 专用环境变量
[env.production.vars]
ENVIRONMENT = "production"