# Cloudflare Workers Configuration for OpenNext.js
name = "aimagica"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# Workers 服务绑定
[services]
binding = "WORKER_SELF_REFERENCE"
service = "aimagica"

# 环境变量配置（Workers）
[env.production.vars]
# 这些需要在Cloudflare Workers控制台中设置
# NEXT_PUBLIC_SUPABASE_URL = "https://vvrkbpnnlxjqyhmmovro.supabase.co"
# NEXT_PUBLIC_SUPABASE_ANON_KEY = "your_anon_key"
# SUPABASE_SERVICE_ROLE_KEY = "your_service_role_key" 