# Cloudflare Workers Configuration for Next.js with OpenNext.js
name = "aimagica"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# 环境变量配置
[env.production.vars]
# 这些需要在Cloudflare Pages控制台中设置
# NEXT_PUBLIC_SUPABASE_URL = "https://vvrkbpnnlxjqyhmmovro.supabase.co"
# NEXT_PUBLIC_SUPABASE_ANON_KEY = "your_anon_key"
# SUPABASE_SERVICE_ROLE_KEY = "your_service_role_key"

# 重定向规则
[[redirects]]
from = "/home"
to = "/"
status = 301

# 安全头部
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# 静态资源缓存
[[headers]]
for = "/_next/static/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# HTML页面缓存策略
[[headers]]
for = "/*.html"
[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

# API路由不缓存
[[headers]]
for = "/api/*"
[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate" 