# Cloudflare Pages Configuration (临时回退)
name = "aimagica"
pages_build_output_dir = ".open-next/assets"
compatibility_date = "2024-12-30"

# 环境变量配置
[env.production.vars]
# 这些需要在Cloudflare Workers控制台中设置
# NEXT_PUBLIC_SUPABASE_URL = "https://vvrkbpnnlxjqyhmmovro.supabase.co"
# NEXT_PUBLIC_SUPABASE_ANON_KEY = "your_anon_key"
# SUPABASE_SERVICE_ROLE_KEY = "your_service_role_key"

# 注意：Workers不支持 redirects 和 headers 配置
# 这些功能需要在Worker代码中实现 