name = "aimagica-auth-worker"
main = "auth-worker.js"
compatibility_date = "2024-01-15"

# 环境变量配置
[env.production]
name = "aimagica-auth-worker"

[env.production.vars]
ENVIRONMENT = "production"
MAIN_API_BASE = "https://aimagica.ai"

# 开发环境
[env.dev]
name = "aimagica-auth-worker-dev"

[env.dev.vars]
ENVIRONMENT = "development"
MAIN_API_BASE = "http://localhost:3000"

# 路由配置
[[env.production.routes]]
pattern = "auth.aimagica.ai/*"
zone_name = "aimagica.ai"

# KV 存储 (如果需要)
# [[kv_namespaces]]
# binding = "AUTH_CACHE"
# id = "your_kv_namespace_id"

# Durable Objects (如果需要)
# [[durable_objects.bindings]]
# name = "SESSION_STORE"
# class_name = "SessionStore"

# 计算限制
[limits]
cpu_ms = 50

# 兼容性标志
[compatibility_flags]
streams_enable_constructors = true 