name = "aimagica-api"
main = "api-worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

# Worker 路由配置
[env.production]
routes = [
  "api.aimagica.ai/*",
  "*.aimagica.ai/api/*"
]

# 环境变量
[env.production.vars]
ENVIRONMENT = "production"

[env.development]
routes = [
  "api-dev.aimagica.ai/*"
]

[env.development.vars]
ENVIRONMENT = "development"

# 资源限制
[limits]
cpu_ms = 30000

# 兼容性设置
[placement]
mode = "smart"

# 计算限制
[limits]
cpu_ms = 50

# 兼容性标志
[compatibility_flags]
streams_enable_constructors = true 